sudo: false

install:
 - pip install coveralls

language: python

python:
  - 2.7

#script: 
#  - python -m unittest discover
script:
  coverage run -m unittest discover

after_success:
    coveralls

